name: OptiProtect
main: Nick3306.github.io.OptiProtect.Main
version: .01
commands:
   Protect:
      description: OptiProtect
      usage:
      permission: 
      permission-message: You do not have permission to use this command!